# Generated by Django 5.0.4 on 2024-04-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Link', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
